name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Link Vercel project
        run: |
          mkdir -p .vercel
          echo '{"projectId":"prj_WSfebMrqmkGFSvh3CfLmAitVYgje","orgId":"team_EBhikDcBBDcyviByUlFAxPvs"}' > .vercel/project.json
        working-directory: frontend

      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: frontend
